# Contains all cinema calenders. This configuration will be merged
# with the default configuration located in the JAR resources.

cinevote:
  webCalendars:
    -
      url: webcal://piffl-medien.de/flk/kalender/kinokalender_friedrichshain.ics
      name: Freiluftkino Friedrichshain
      shortName: Friedrichshain
      style: theme1
    -
      url: webcal://piffl-medien.de/flk/kalender/kinokalender_kreuzberg.ics
      name: Freiluftkino Kreuzberg
      shortName: Kreuzberg
      style: theme2
    -
      url: https://posteo.de/calendars/ics/syw283vawr6norq8t1kkn8q0rntrgvgi
      name: Sommerkino Kulturforum
      shortName: Sommerkino
      style: theme3
    -
      url: https://posteo.de/calendars/ics/nnmxmpjmafhxo8dtn9lvbed78g7ofgvp
      name: Freiluftkino Hasenheide
      shortName: Hasenheise
      style: theme4
    -
      url: webcal://piffl-medien.de/flk/kalender/kinokalender_rehberge.ics
      name: Freiluftkino Rehberge
      shortName: Rehberge
      style: theme5

