server.port: 9998

cinevote:
  webCalendars:
    -
      url: webcal://piffl-medien.de/flk/kalender/kinokalender_friedrichshain.ics
      name: Freiluftkino Friedrichshain
      style: theme1
    -
      url: webcal://piffl-medien.de/flk/kalender/kinokalender_kreuzberg.ics
      name: Freiluftkino Kreuzberg
      style: theme2
    -
      url: https://posteo.de/calendars/ics/syw283vawr6norq8t1kkn8q0rntrgvgi
      name: Sommerkino Kulturforum
      style: theme3