# This file is shipped with the JAR and serves as base configuration.
# It is recommended to create an application.yml file and place it next to
# the JAR which contains the settings for productive mode with all calendars.

server.port: 9998

cinevote:
  dateFormat: "EEE, d. MMMMM '-' HH:mm 'Uhr'"

  dayView:
    firstVisibleHourOfDay: 19
    lastVisibleHourOfDay: 23